'use client';
import {useState} from 'react';
import type {ArtifactPage,DiscussionPage} from '@/receiver/vendor/investment/v1/types';
import type {ArchiveResponse} from '@/lib/investment-archive';
import {artifactHref,inRun} from '@/lib/investment-links';
import {publicRead} from './desk';
export function ArchiveCollections({artifacts,discussions,run}:{artifacts:ArchiveResponse<ArtifactPage>;discussions:ArchiveResponse<DiscussionPage>;run?:string}){
 const [a,setA]=useState(artifacts),[d,setD]=useState(discussions),[busy,setBusy]=useState(false);
 async function load(kind:'artifacts'|'discussions',after?:string){setBusy(true);try{if(kind==='artifacts')setA(await publicRead<ArtifactPage>('artifacts?limit=20'+(after?'&after='+encodeURIComponent(after):''),run));else setD(await publicRead<DiscussionPage>('discussions?limit=20'+(after?'&after='+encodeURIComponent(after):''),run));}catch{const error={data:null,error:'Archive unavailable. Current visibility could not be verified.'} as const;if(kind==='artifacts')setA(error);else setD(error);}finally{setBusy(false);}}
 return <><div className="inv-library" aria-busy={busy}>{a.data&&!a.data.items.length&&<p className="inv-empty">No public deliverables are registered.</p>}{a.data?a.data.items.map(item=><article key={item.registration.artifactId}><span className="inv-kicker">Deliverable · {item.status.replaceAll('_',' ')}</span><h3>{item.registration.title}</h3><p>{item.safeReason??'Exact published evidence; corrections preserve earlier versions.'}</p><a href={artifactHref(item.registration.artifactId,item.currentPublishedVersion??1,run)}>{item.currentPublishedVersion?'Open version '+item.currentPublishedVersion:'Inspect publication state'} →</a></article>):<p role="status">{a.error}</p>}</div><div className="inv-actions"><button disabled={busy} onClick={()=>void load('artifacts')}>First deliverables page / refresh</button>{a.data?.nextCursor&&<button disabled={busy} onClick={()=>void load('artifacts',a.data!.nextCursor!)}>Next deliverables</button>}</div><details className="inv-details"><summary>Browse discussion archive</summary>{d.data&&!d.data.items.length&&<p>No public discussions are registered.</p>}{d.data?<ul>{d.data.items.map(t=><li key={t.discussionId}><a href={inRun('/botsquad/investment/discussions/'+t.discussionId,run)}>{t.topic}</a><p>{t.charter}</p></li>)}</ul>:<p role="status">{d.error}</p>}<div className="inv-actions"><button disabled={busy} onClick={()=>void load('discussions')}>First discussions page</button>{d.data?.nextCursor&&<button disabled={busy} onClick={()=>void load('discussions',d.data!.nextCursor!)}>Next discussions</button>}</div></details></>;
}
