'use client';
import { useState } from 'react';
import type { TransactionPage } from '@/receiver/vendor/investment/v1/types';
import type { ArchiveResponse } from '@/lib/investment-archive';
import { displayTime, inRun, money, recordHref } from '@/lib/investment-links';
import { publicRead } from './desk';
import { ExportButtons } from './export';
import { AskPreview } from './ask-preview';
export function Journal({initial,run,synthetic,slippage}:{initial:ArchiveResponse<TransactionPage>;run?:string;synthetic:boolean;slippage?:number}) {
  const [page,setPage]=useState(initial),[instrument,setInstrument]=useState(''),[action,setAction]=useState(''),[status,setStatus]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[busy,setBusy]=useState(false);
  const rows=page.data?.items.filter(({event:e})=>{
    const p=e.payload,fill=e.type==='paper.ledger_transaction'?e.payload.fill:null;
    const id=e.type==='paper.order'?e.payload.instrumentId:fill?.instrumentId??'',side=e.type==='paper.order'?e.payload.side:fill?.side??'',state=e.type==='paper.order'?e.payload.status:p&&'effect'in p?p.effect:'';
    const date=(e.type==='paper.ledger_transaction'?e.payload.effectiveAt:e.occurredAt).slice(0,10);
    return (!instrument||id.toLowerCase().includes(instrument.toLowerCase()))&&(!action||side===action)&&(!status||state===status)&&(!from||date>=from)&&(!to||date<=to);
  })??[];
  async function load(after?:string){setBusy(true);try{const result=await publicRead<TransactionPage>('transactions?limit=20'+(after?'&after='+encodeURIComponent(after):''),run);setPage(result);}catch{setPage({data:null,error:'Journal unavailable. Current visibility could not be verified.'});}finally{setBusy(false);}}
  const exportRows=rows.map(({event:e})=>e.type==='paper.order'?[e.occurredAt,e.payload.orderId,e.payload.instrumentId,e.payload.side,e.payload.quantity,null,e.payload.status,e.payload.decisionId,e.payload.reason]:[e.payload.effectiveAt,e.payload.transactionId,e.payload.fill?.instrumentId??null,e.payload.fill?.side??null,e.payload.fill?.quantity??null,e.payload.fill?.price??null,e.payload.effect,e.payload.fill?.decisionId??null,e.payload.correctionOf?.id??null]);
  return <><div className="inv-toolbar"><label>Instrument<input value={instrument} onChange={e=>setInstrument(e.target.value)} placeholder="Instrument ID"/></label><label>Action<select value={action} onChange={e=>setAction(e.target.value)}><option value="">All actions</option><option>BUY</option><option>SELL</option></select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['proposed','validated','pending','filled','rejected','expired','cancelled','fill','initialization','dividend_accrual','dividend_payment','correction'].map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></label><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Through<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><p className="inv-meta">Filters and exports apply to the current page of up to 20 immutable records. Order revisions are separate from simulated fills. Slippage: {slippage===undefined?'unconfigured':slippage+' basis points, already included in fill price'}.</p>{from&&to&&from>to&&<p role="alert">The start date must precede the end date.</p>}
    <div className="inv-journal" aria-busy={busy}>{!page.data?<p role="status">{page.error}</p>:!rows.length?<p className="inv-empty">No records match this page and these filters.</p>:rows.map(({event:e})=>{
      const isOrder=e.type==='paper.order',p=e.payload,id=isOrder?e.payload.orderId:e.payload.transactionId,fill=!isOrder?e.payload.fill:null;
      const decision=isOrder?e.payload.decisionId:fill?.decisionId;
      return <article key={e.eventId}><div className="inv-card-heading"><h3>{isOrder?`${e.payload.side} proposal · ${e.payload.status}`:fill?`${fill.side} · simulated fill`:e.payload.effect.replaceAll('_',' ')}</h3><span className="inv-badge">{isOrder?'Order v'+e.payload.revision:'Ledger #'+e.payload.journalSequence}</span></div><p className="inv-meta">{displayTime(e.occurredAt)} · {id}</p><p>{isOrder?`${e.payload.quantity} shares · ${e.payload.instrumentId}`:fill?`${fill.quantity} shares · ${fill.instrumentId} at ${money(fill.price)}`:'A typed ledger effect; no discretionary order is implied.'}</p>{isOrder&&e.payload.reason&&<p>{e.payload.reason}</p>}{fill&&<p className="inv-meta">Fee {money(fill.fee)} · {fill.observation.provider} / {fill.observation.feed} · {fill.observation.field.replaceAll('_',' ')}<br/>Price as of {displayTime(fill.observation.marketAt)} · retrieved {displayTime(fill.observation.retrievedAt)} · configured delay {fill.observation.delaySeconds}s</p>}{!isOrder&&<><p>Cash impact: {p&&'entries'in p?p.entries.filter(x=>x.account==='cash').map(x=>money(x.amount)).join(', ')||'No cash entry':'Unavailable'}</p>{e.payload.correctionOf&&<a href={recordHref(e.payload.correctionOf,run)}>Corrects {e.payload.correctionOf.id}</a>}</>}<div className="inv-actions">{decision&&<a href={inRun('/botsquad/investment/decisions/'+decision,run)}>Inspect decision →</a>}<a href={recordHref({kind:isOrder?'order':'transaction',id,version:isOrder?e.payload.revision:1,relation:'results_in'},run)}>Exact record & receipt →</a></div><details><summary>Ask about this {isOrder?'order':'trade'} · unavailable</summary><AskPreview context={{experimentId:e.experimentId,runId:e.runId,record:{kind:isOrder?'order':'transaction',id,version:isOrder?e.payload.revision:1,relation:'supports'}}}/></details></article>;
    })}</div><div className="inv-actions"><button disabled={busy} onClick={()=>void load()}>First journal page / refresh</button>{page.data?.nextCursor&&<button disabled={busy} onClick={()=>void load(page.data!.nextCursor!)}>Next journal page</button>}</div><ExportButtons synthetic={synthetic} name="journal-page" records={rows} rows={[["Time","Record","Instrument","Action","Quantity","Price USD","Status / effect","Decision","Reason / correction"],...exportRows]}/></>;
}
