'use client';
import { useState } from 'react';
import type { PortfolioSnapshot, RunConfiguration } from '@/receiver/vendor/investment/v1/types';
import { decimalSum, displayTime, money, percent, ratio, recordHref } from '@/lib/investment-links';
import {benchmarkDrawdowns} from '@/lib/investment-performance';
import { ExportButtons } from './export';
export function currentValuations(items:PortfolioSnapshot[]):PortfolioSnapshot[] {
  const latest=new Map<string,PortfolioSnapshot>();
  for(const s of items)if(!latest.has(s.valuationId)||latest.get(s.valuationId)!.revision<s.revision)latest.set(s.valuationId,s);
  return [...latest.values()].sort((a,b)=>a.valuationSequence===b.valuationSequence?0:BigInt(a.valuationSequence)<BigInt(b.valuationSequence)?-1:1);
}
export function Portfolio({snapshot,history,configuration,synthetic,run,hasMore,completeHistory}:{snapshot:PortfolioSnapshot|null;history:PortfolioSnapshot[];configuration?:RunConfiguration;synthetic:boolean;run?:string;hasMore:boolean;completeHistory:boolean}) {
  const [sort,setSort]=useState('symbol'),[filter,setFilter]=useState(''),[view,setView]=useState('all');
  const points=currentValuations(history),shown=view==='recent'?points.slice(-5):points;
  const holdings=[...(snapshot?.holdings??[])].filter(h=>`${h.symbol} ${h.instrumentId} ${h.sector}`.toLowerCase().includes(filter.toLowerCase())).sort((a,b)=>sort==='value'?(Number(b.marketValue??-1)-Number(a.marketValue??-1)):sort==='result'?Number(b.unrealizedPnl??-Infinity)-Number(a.unrealizedPnl??-Infinity):a.symbol.localeCompare(b.symbol));
  const benchmarkDrawdown=benchmarkDrawdowns(points,completeHistory?configuration?.initialCapital:undefined),shownDrawdowns=view==='recent'?benchmarkDrawdown.slice(-5):benchmarkDrawdown;
  const latest=points.at(-1),incomplete=latest?.quality!=='complete'&&!!latest;
  const metrics:[string,string][]=[['Starting capital',money(configuration?.initialCapital)],['Last complete equity',money(snapshot?.equity)],['Available cash',money(snapshot?.cash)],['Total return',percent(snapshot?.totalReturn)],['Daily change',percent(snapshot?.dailyReturn)],['Realized result',money(snapshot?.realizedPnl)],['Unrealized result',money(snapshot?.unrealizedPnl)],['Dividend receivables',money(snapshot?.receivables)],['Dividend income','Not supplied by snapshot'],['Benchmark return',percent(snapshot?.benchmark.totalReturn)],['Excess return',snapshot?.excessReturn==null?'Unavailable':percent(snapshot.excessReturn).replace('%',' pp')],['Maximum drawdown',percent(snapshot?.maxDrawdown)]];
  return <><p className="inv-meta">{synthetic?'Synthetic portfolio · ':''}USD · last complete valuation: {displayTime(snapshot?.valuationAsOf??null)}. Snapshot quality: {snapshot?.quality??'unknown'}; this does not establish fresh market data.</p>{incomplete&&<p className="inv-warning">A newer {latest.quality} observation exists. Last complete values below are retained history; the incomplete point remains a gap.</p>}
    <dl className="inv-metrics">{metrics.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>
    <div className="inv-chart-heading"><div><h3>Performance, in context.</h3><p>Portfolio and benchmark returns use the same configured starting capital. Excess return is measured in percentage points.</p></div><label>Chart window<select value={view} onChange={e=>setView(e.target.value)}><option value="all">All loaded observations</option><option value="recent">Last five observations</option></select></label></div>
    <div className="inv-chart-grid"><LineChart points={shown} title="Portfolio vs benchmark" field="return" synthetic={synthetic}/><LineChart points={shown} title="Drawdown comparison" field="drawdown" synthetic={synthetic} benchmarkDrawdown={shownDrawdowns}/></div>
    <p className="inv-meta">{configuration?.attribution??'Source not configured.'} Delay: {configuration?configuration.dataDelaySeconds+' seconds (configured)':'unknown'}. Range: {shown[0]?.session??'unavailable'} to {shown.at(-1)?.session??'unavailable'}. Missing observations are gaps. Highest available revision per valuation is shown; exact prior versions remain in the archive. {hasMore?'This is a bounded page, not the complete performance history.':''}</p>
    <details className="inv-details"><summary>Performance data & exact revisions</summary><div className="inv-table-wrap" tabIndex={0} role="region" aria-label="Performance data table"><table><caption>{synthetic?'Synthetic ':''}performance observations · returns and drawdown in percent</caption><thead><tr>{['Session / version','Equity (USD)','Portfolio','Benchmark','Drawdown','Benchmark drawdown (derived)','Quality'].map(x=><th key={x} scope="col">{x}</th>)}</tr></thead><tbody>{shown.map((s,i)=><tr key={s.valuationId}><th scope="row"><a href={recordHref({kind:'valuation',id:s.valuationId,version:s.revision,relation:'supports'},run)}>{s.session} · v{s.revision}</a></th><td>{money(s.equity)}</td><td>{percent(s.totalReturn)}</td><td>{percent(s.benchmark.totalReturn)}</td><td>{percent(s.drawdown)}</td><td>{percent(shownDrawdowns[i])}</td><td>{s.quality}</td></tr>)}</tbody></table></div></details>
    <ExportButtons synthetic={synthetic} name="performance-page" records={shown} rows={[["Session","Version","Equity USD","Portfolio ratio","Benchmark ratio","Drawdown ratio","Derived benchmark drawdown ratio","Quality"],...shown.map((s,i)=>[s.session,s.revision,s.equity,s.totalReturn,s.benchmark.totalReturn,s.drawdown,shownDrawdowns[i]??null,s.quality])]}/>
    <div className="inv-chart-grid inv-allocation"><Allocation snapshot={snapshot} kind="position"/><Allocation snapshot={snapshot} kind="sector"/></div>
    <h3 className="inv-subheading">Positions & cost basis</h3><p className="inv-meta">Book cost includes modeled fees. Position realized results are not supplied by this contract; the portfolio total appears above.</p>
    <div className="inv-toolbar"><label>Find a holding<input type="search" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Symbol, sector or instrument"/></label><label>Sort holdings<select value={sort} onChange={e=>setSort(e.target.value)}><option value="symbol">Symbol A–Z</option><option value="value">Market value, highest first</option><option value="result">Unrealized result, highest first</option></select></label></div>
    <div className="inv-holdings">{holdings.length?holdings.map(h=><article className="inv-holding" key={h.instrumentId}><div className="inv-card-heading"><h4>{h.symbol}</h4><span>{h.sector||'Unknown classification'}</span></div><p className="inv-meta">{h.instrumentId} · quantity {h.quantity}</p><dl><div><dt>Book cost</dt><dd>{money(h.bookCost)}</dd></div><div><dt>Current mark</dt><dd>{money(h.mark?.value)}</dd></div><div><dt>Market value</dt><dd>{money(h.marketValue)}</dd></div><div><dt>Portfolio weight</dt><dd>{percent(ratio(h.marketValue,snapshot?.equity??null)).replace(/^\+/, '')}</dd></div><div><dt>Unrealized result</dt><dd>{money(h.unrealizedPnl)}</dd></div></dl><figure className="inv-position-bars" aria-label={`${h.symbol} book cost ${money(h.bookCost)}, market value ${money(h.marketValue)}`}><div><span>Cost</span><meter min={0} max={Math.max(Number(h.bookCost),Number(h.marketValue??0),1)} value={Number(h.bookCost)} aria-label={`${h.symbol} book cost`}/><span>{money(h.bookCost)}</span></div><div><span>Value</span>{h.marketValue===null?<span>Unavailable</span>:<meter min={0} max={Math.max(Number(h.bookCost),Number(h.marketValue),1)} value={Number(h.marketValue)} aria-label={`${h.symbol} market value`}/>}<span>{money(h.marketValue)}</span></div><figcaption>Cost and current value · USD</figcaption></figure><p className="inv-meta">Mark as of {displayTime(h.mark?.marketAt??null)}. {h.mark?`${h.mark.provider} / ${h.mark.feed} · ${h.mark.delaySeconds}s configured delay · ${snapshot?.quality}`:h.missingReason??'No mark published.'}</p></article>):<p className="inv-empty">No holdings available in this view. Unknown holdings are not a zero balance.</p>}</div>
    <details className="inv-details"><summary>Holdings data table</summary><div className="inv-table-wrap" tabIndex={0} role="region" aria-label="Holdings data table"><table><caption>Holdings in the last complete snapshot · USD values</caption><thead><tr>{['Instrument','Quantity','Book cost','Mark','Value','Weight','Unrealized','Sector','Mark time / quality'].map(x=><th key={x} scope="col">{x}</th>)}</tr></thead><tbody>{holdings.map(h=><tr key={h.instrumentId}><th scope="row">{h.symbol}</th><td>{h.quantity}</td><td>{money(h.bookCost)}</td><td>{money(h.mark?.value)}</td><td>{money(h.marketValue)}</td><td>{percent(ratio(h.marketValue,snapshot?.equity??null)).replace(/^\+/, '')}</td><td>{money(h.unrealizedPnl)}</td><td>{h.sector||'Unknown'}</td><td>{displayTime(h.mark?.marketAt??null)} / {h.mark?snapshot?.quality:'missing'}</td></tr>)}</tbody></table></div></details>
  </>;
}
function LineChart({points,title,field,synthetic,benchmarkDrawdown}:{points:PortfolioSnapshot[];title:string;field:'return'|'drawdown';synthetic:boolean;benchmarkDrawdown?:(string|null)[]}) {
  const portfolio=points.map(s=>s.quality==='complete'?(field==='return'?s.totalReturn:s.drawdown):null);
  const benchmark=field==='return'?points.map(s=>s.benchmark.totalReturn):benchmarkDrawdown??[];
  const summary=field==='return'?`Latest loaded portfolio return ${percent(portfolio.at(-1))}; benchmark ${percent(benchmark.at(-1))}.`:`Latest loaded portfolio drawdown ${percent(portfolio.at(-1))}; derived benchmark drawdown ${percent(benchmark.at(-1))}.`;

  const values=[...portfolio,...benchmark].filter((n):n is string=>n!==null).map(n=>Number(n)*100),lo=Math.min(0,...values),hi=Math.max(0,...values),span=Math.max(hi-lo,1),bottom=lo===hi?lo-0.5:lo,top=lo===hi?hi+0.5:hi;
  const x=(i:number)=>52+(i/Math.max(points.length-1,1))*410,y=(n:number)=>32+(top-n)/(top-bottom||span)*150;
  const path=(series:(string|null)[])=>{let gap=true;return series.map((n,i)=>{if(n===null){gap=true;return '';}const text=`${gap?'M':'L'}${x(i)},${y(Number(n)*100)}`;gap=false;return text;}).join(' ');};
  return <figure className="inv-chart"><figcaption><strong>{title}</strong><span>{synthetic?'Synthetic demonstration · ':''}percent (%)</span></figcaption>{values.length?<svg viewBox="0 0 500 224" role="img" aria-label={`${title}. ${points.length} observations, ${portfolio.filter(x=>x===null).length} gaps. Underlying values follow in the data table.`}><title>{title}</title><desc>{summary}</desc>{[top,(top+bottom)/2,bottom].map((v,i)=><g key={i}><line x1="52" x2="462" y1={y(v)} y2={y(v)} className="inv-gridline"/><text x="44" y={y(v)+4} textAnchor="end">{v.toFixed(1)}%</text></g>)}<path d={path(portfolio)} className="inv-line"/>{benchmark.length>0&&<path d={path(benchmark)} className="inv-line inv-line--benchmark"/>}{portfolio.map((n,i)=>n!==null?<circle key={i} cx={x(i)} cy={y(Number(n)*100)} r="3" className="inv-point"/>:<text key={i} x={x(i)} y="200" textAnchor="middle">gap</text>)}<text x="52" y="219">{points[0]?.session.slice(5)}</text><text x="462" y="219" textAnchor="end">{points.at(-1)?.session.slice(5)}</text></svg>:<p className="inv-empty">No comparable observations. No line is drawn.</p>}<p>{summary} {portfolio.filter(x=>x===null).length} missing portfolio observations remain gaps.</p><p className="inv-legend"><span>━ Portfolio · circles</span>{benchmark.length>0&&<span>┄ Benchmark · dashed</span>}</p><p className="inv-meta">{field==='return'?'Both series use their configured equal initial capital. No gaps are interpolated.':benchmark.some(x=>x!==null)?'Portfolio drawdown is published. Benchmark drawdown is derived from its equity peaks across the complete loaded history and initial capital.':'Portfolio drawdown is published. Comparable benchmark drawdown is unavailable for a partial history, missing peak or missing benchmark observation.'}</p></figure>;
}
function Allocation({snapshot,kind}:{snapshot:PortfolioSnapshot|null;kind:'position'|'sector'}) {
  const groups=new Map<string,string|null>();
  for(const h of snapshot?.holdings??[]){const name=kind==='position'?h.symbol:h.sector||'Unknown classification';const prior=groups.get(name);groups.set(name,h.marketValue===null||prior===null?null:decimalSum([prior??'0',h.marketValue]));}
  if(snapshot)groups.set('Cash',snapshot.cash);
  const equity=snapshot?.equity?Number(snapshot.equity):null;
  return <figure className="inv-chart"><figcaption><strong>{kind==='position'?'Asset allocation':'Sector allocation'}</strong><span>Last complete snapshot · weight of equity</span></figcaption>{groups.size?<><ul className="inv-bars">{[...groups].map(([label,value])=><li key={label}><div><strong>{label}</strong><span>{equity&&value!==null?(Number(value)/equity*100).toFixed(2)+'%':'Unavailable'}</span></div>{equity&&value!==null&&<meter min={0} max={100} value={Math.max(0,Math.min(100,Number(value)/equity*100))} aria-label={`${label} allocation`}/>}</li>)}</ul><p className="inv-meta">Receivables {money(snapshot?.receivables)}; liabilities {money(snapshot?.liabilities)}. Weights may not total 100% when either is present. Classifications come from the record.</p><details><summary>Allocation data</summary><table><caption>{kind==='position'?'Position':'Sector'} allocation · USD</caption><thead><tr><th scope="col">Category</th><th scope="col">Value</th><th scope="col">Weight</th></tr></thead><tbody>{[...groups].map(([label,value])=><tr key={label}><th scope="row">{label}</th><td>{money(value)}</td><td>{equity&&value!==null?(Number(value)/equity*100).toFixed(2)+'%':'Unavailable'}</td></tr>)}</tbody></table></details></>:<p className="inv-empty">No allocation published.</p>}</figure>;
}
