import type {Event,RecordRef} from '@/receiver/vendor/investment/v1/types';
import {displayTime,money,percent} from '@/lib/investment-links';
import {Links,Sources} from './archive';
import {AskPreview} from './ask-preview';
/** Human-readable evidence keeps nested contract references navigable; raw data stays optional. */
export function RecordDetail({event:e,record,run}:{event:Event;record:RecordRef;run?:string}) {
 let content,refs:RecordRef[]=[...e.references];
 switch(e.type){
 case 'review.published':refs=[...refs,...e.payload.originalDecisions,...e.payload.observations];content=<><h2>Outcome review</h2><p>{e.payload.interpretation}</p><p>As of {displayTime(e.payload.asOf)} · Next disposition: {e.payload.nextDisposition}</p><h3>Limitations</h3><ul>{e.payload.limitations.map(x=><li key={x}>{x}</li>)}</ul></>;break;
 case 'discussion.contribution':refs=[...refs,...e.payload.evidence,{kind:'discussion',id:e.payload.discussionId,version:1,relation:'supports'},...(e.payload.replyTo?[{kind:'contribution' as const,id:e.payload.replyTo,version:1,relation:'supports' as const}]:[])];content=<><h2>Discussion contribution</h2><p>{e.payload.body}</p><p>Contribution {e.payload.ordinal}</p></>;break;
 case 'paper.order':refs.push({kind:'decision',id:e.payload.decisionId,version:e.payload.decisionRevision,relation:'results_in'});content=<><h2>{e.payload.side} order · {e.payload.status}</h2><p>{e.payload.quantity} shares · {e.payload.instrumentId}</p><p>{e.payload.reason??'No additional reason published.'}</p><p>Target session {e.payload.targetSession}; expires {displayTime(e.payload.expiresAt)}. This order state is separate from a completed fill.</p></>;break;
 case 'paper.ledger_transaction':{const p=e.payload,f=p.fill;if(p.correctionOf)refs.push(p.correctionOf);if(f)refs.push({kind:'decision',id:f.decisionId,version:f.decisionRevision,relation:'results_in'},{kind:'order',id:f.orderId,version:f.orderRevision,relation:'results_in'});content=<><h2>{p.effect.replaceAll('_',' ')}</h2><p>Effective {displayTime(p.effectiveAt)} · Ledger sequence {p.journalSequence}</p>{f&&<><p>{f.side} {f.quantity} shares · {f.instrumentId} at {money(f.price)}. Fee: {money(f.fee)}.</p><p>Price source: {f.observation.provider} / {f.observation.feed} · {f.observation.field.replaceAll('_',' ')}. Market observation {displayTime(f.observation.marketAt)}; retrieved {displayTime(f.observation.retrievedAt)}; configured delay {f.observation.delaySeconds}s.</p></>}<div className="inv-table-wrap" tabIndex={0} role="region" aria-label="Ledger entries"><table><caption>Immutable ledger entries · account units</caption><thead><tr><th scope="col">Account</th><th scope="col">Amount</th></tr></thead><tbody>{p.entries.map((x,i)=><tr key={i}><th scope="row">{x.account}</th><td>{x.account==='quantity'?x.amount+' shares':money(x.amount)}</td></tr>)}</tbody></table></div></>;break;}
 case 'portfolio.snapshot':content=<><h2>Valuation · {e.payload.session}</h2><p>Revision {e.payload.revision} · Quality: {e.payload.quality}. As of {displayTime(e.payload.valuationAsOf)}.</p><dl className="inv-metrics">{[['Equity',money(e.payload.equity)],['Cash',money(e.payload.cash)],['Return',percent(e.payload.totalReturn)],['Benchmark return',percent(e.payload.benchmark.totalReturn)],['Drawdown',percent(e.payload.drawdown)]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><ul>{e.payload.limitations.map(x=><li key={x}>{x}</li>)}</ul></>;break;
 case 'decision.published':refs=[...refs,...e.payload.proposal.evidence];content=<><h2>{e.payload.proposal.action} · decision revision {e.payload.proposal.revision}</h2><p>{e.payload.proposal.rationale}</p><p>Review disposition: {e.payload.review.disposition}</p><h3>Dissent</h3><ul>{e.payload.review.dissent.map(x=><li key={x}>{x}</li>)}</ul><Sources sources={e.payload.proposal.sources}/></>;break;
 default:content=<><h2>{e.type.replaceAll('.',' / ')}</h2><p>This exact public record is retained below with its receipt and original timestamps.</p></>;
 }
 return <>{content}<h2>Related evidence</h2><Links refs={refs} run={run}/><AskPreview context={{experimentId:e.experimentId,runId:e.runId,record}}/><details><summary>Inspect typed record data</summary><pre className="archive-body">{JSON.stringify(e.payload,null,2)}</pre></details></>;
}
