import { Suspense } from 'react';
import { SiteHeader } from '@/components/site-header';
import { SiteFooter } from '@/components/site-footer';
import { investmentArchive, investmentShowcase as copy } from '@/content/site';
import { actorName, displayTime, inRun, recordHref } from '@/lib/investment-links';
import { readShowcase } from '@/lib/investment-showcase';
import { Desk } from './desk';
import { PerformanceHistory } from './performance-history';
import { Journal } from './journal';
import { AskPreview } from './ask-preview';
import { VisibilityBoundary } from './visibility-boundary';
import { RunHistory } from './run-history';
import { ArchiveCollections } from './collections';
async function ShowcaseRecords({run}:{run?:string}) {
  const data=await readShowcase(run),events=(data.events.data?.items??[]).map(x=>x.event).sort((a,b)=>a.sourceSequence===b.sourceSequence?0:BigInt(a.sourceSequence)<BigInt(b.sourceSequence)?-1:1);
  const configuration=events.find(e=>e.type==='run.published'),roster=events.filter(e=>e.type==='team.published').at(-1),workers=roster?.type==='team.published'?roster.payload.workers:[];
  const synthetic=configuration?.evidenceMode==='synthetic_fixture'||process.env.ASYMMETRI_INVESTMENT_EVIDENCE_MODE==='synthetic_fixture';
  const selectedRun=data.run,runPayload=configuration?.type==='run.published'?configuration.payload:undefined;
  const decisions=events.filter(e=>e.type==='decision.published'),activities=events.filter(e=>e.type==='worker.activity'),state=data.status.data;
  const latestRunState=events.filter(e=>e.type==='run.status').at(-1);
  // Failure to verify run/mode cannot turn fixture financial records into observed data.
  if(!runPayload)return <><section className="inv-health"><h2>Official experiment not started</h2><p>No verified run configuration and evidence mode are available. Published records remain unavailable until both can be verified. No worker activity, portfolio value or trade is inferred.</p><p>{data.events.error??'Run configuration is not present in the first event page.'}</p><a href={run?'/botsquad/investment/runs/'+run:'/botsquad/investment'}>Retry archive verification →</a></section>{copy.navigation.filter(([id])=>id!=='ask').map(([id,label])=><section className="inv-section" id={id} key={id}><h2>{label}</h2><p className="inv-empty">No public records are available for this section. The official run remains unconfigured.</p></section>)}<section id="ask" className="inv-section"><h2>Ask preview</h2><AskPreview/></section></>;


  return <>{synthetic&&process.env.ASYMMETRI_INVESTMENT_EVIDENCE_MODE!=="synthetic_fixture"&&<div className="inv-synthetic" role="note">{investmentArchive.synthetic}</div>}    <VisibilityBoundary revision={data.status.data?data.status.fingerprint:undefined} run={selectedRun} enabled={!!process.env.ASYMMETRI_INVESTMENT_READ_ORIGIN}><section className="inv-health" aria-labelledby="health-title"><div><p className="inv-kicker">Experiment status</p><h2 id="health-title">{synthetic?'Recorded synthetic demonstration':state?state.state.replaceAll('_',' '):'Not started'}</h2><p>{runPayload?.title??'No official investment run is published.'}</p>{selectedRun&&<a href={'/botsquad/investment/runs/'+selectedRun}>Exact run: {selectedRun} ↗</a>}</div><dl><div><dt>Run state</dt><dd>{state?.state??'Unconfigured'}</dd></div><div><dt>Publication health</dt><dd>{state?.freshness.status??'Unknown'}</dd></div><div><dt>Last publication</dt><dd>{displayTime(state?.freshness.lastPublicationAt??null)}</dd></div><div><dt>Next authorized review</dt><dd>{latestRunState?.type==='run.status'?displayTime(latestRunState.payload.nextReviewAt):'Unconfigured'}</dd></div></dl><p className="inv-meta">{state?.freshness.reason??data.status.error} {state?.watermark.sourceGaps?'Public evidence has gaps.':''} Market state is unverified.</p><RunHistory initial={data.experiment}/></section>
    <section className="inv-section" id="team"><SectionHeading number="01" title="Meet the team." description={synthetic?'Example identities and assignments, created only for this demonstration. No portrait or activity implies a real employee.':'Participating workers from the published roster. No activity is inferred from availability alone.'}/><div className="inv-team">{workers.length?workers.map(w=>{const activity=activities.filter(e=>e.payload.workerId===w.workerId).at(-1);const status=w.status==='unavailable'||w.status==='retired'?'Unavailable':activity?.payload.finishedAt?'Completed':activity?.payload.activity==='idle'?'Idle':state?.freshness.status==='fresh'&&activity&&activity.payload.activity!=='blocked'?'Working':'Unknown';return <article key={w.workerId}><div className="inv-worker-mark" aria-hidden="true">{w.name.split(' ').slice(0,2).map(n=>n[0]).join('')}</div><p className="inv-kicker">{w.role}</p><h3>{w.name}</h3><p>{w.responsibilities.join(' ')}</p><span className="inv-badge">{synthetic?'Example · ':''}{status}</span><p className="inv-meta">Last recorded activity: {displayTime(activity?.occurredAt??null)}</p>{activity?.payload.work&&<a href={recordHref(activity.payload.work,selectedRun)}>Inspect related work →</a>}</article>;}):<p className="inv-empty">No verified investment roster is published. Employee names, assignments and activity will appear only after trusted publication.</p>}</div><p className="inv-meta">Working, queued, idle, unavailable and completed are distinct states. This v1 archive does not publish a queue state. Missing or stale activity stays unknown. {data.events.data?.nextCursor?'Roster and activities are limited to this event window; newer assignments may exist.':''}</p></section>
    <section className="inv-section" id="desk"><SectionHeading number="02" title="The Live Investment Desk." description="Follow the research, the objections and what the team concluded. System records remain distinct from employee contributions."/><Desk initial={data.events} run={selectedRun} workers={workers} topics={data.discussions.data?.items??[]} synthetic={synthetic}/></section>
    <section className="inv-section" id="portfolio"><SectionHeading number="03" title="A measurable outcome." description="Read the portfolio alongside the work that produced it. Financial values come from typed snapshots, never from discussion text."/><PerformanceHistory initial={data.performance} snapshot={data.snapshot.data?.snapshot??null} configuration={runPayload?.configuration} synthetic={synthetic} run={selectedRun}/></section>
    <section className="inv-section" id="decisions"><SectionHeading number="04" title="Decisions, with a paper trail." description="A recommendation, an accepted order and a completed simulated fill are different records. A decision to wait belongs here too."/><div className="inv-decision-grid">{decisions.length?decisions.map(e=><article key={e.eventId}><div className="inv-card-heading"><span className="inv-action-label">{e.payload.proposal.action}</span><span className="inv-badge">Review: {e.payload.review.disposition}</span></div><p>{e.payload.proposal.rationale}</p><p className="inv-meta">{actorName(e.actor,workers)} · {displayTime(e.payload.proposal.committedAt)} · revision {e.payload.proposal.revision}</p><a href={inRun('/botsquad/investment/decisions/'+e.payload.proposal.decisionId,selectedRun)}>Evidence, dissent & outcome →</a></article>):<p className="inv-empty">No public decisions. No recommendations or simulated actions are generated to fill this page.</p>}</div>{data.events.data?.nextCursor&&<p>Only decisions in the loaded event window are shown. Browse later event pages in the desk for additional decisions.</p>}</section>
    <section className="inv-section" id="research"><SectionHeading number="05" title="Open the research." description="Published reports keep permanent exact-version links. Every registered deliverable has a visible publication state, including material that cannot be shown."/><ArchiveCollections artifacts={data.artifacts} discussions={data.discussions} run={selectedRun}/></section>
    <section className="inv-section" id="journal"><SectionHeading number="06" title="The transaction journal." description="Read-only records of simulated financial actions, rejected requests and corrections. No public trading controls."/><Journal initial={data.transactions} run={selectedRun} synthetic={synthetic} slippage={runPayload?.configuration.slippageBps}/></section>
    <section className="inv-section" id="method"><SectionHeading number="07" title="How the work connects." description="Persistent employees, bounded assignments and inspectable evidence. A review can change the next decision without rewriting the old one."/><ol className="inv-process">{copy.process.map(([title,body],i)=><li key={title}><span aria-hidden="true">0{i+1}</span><h3>{title}</h3><p>{body}</p></li>)}</ol><div className="inv-method"><h3>Know the limits.</h3><p>Official capital, universe, risk limits, source permissions and dates remain unconfigured. The local demonstration uses author-created values. Real market integration and a forward-running trial are separate milestones.</p><a href={inRun('/botsquad/investment/methodology',selectedRun)}>Methodology, data quality & interventions →</a></div></section>
    <section className="inv-section" id="ask"><SectionHeading number="08" title="Eventually, ask the team." description="The planned service will connect a question to one relevant actual employee and the exact evidence under discussion."/><AskPreview/></section>
    </VisibilityBoundary></>;
}
export function Showcase({run}:{run?:string}) {
 const selectedRun=run??process.env.ASYMMETRI_INVESTMENT_RUN,synthetic=process.env.ASYMMETRI_INVESTMENT_EVIDENCE_MODE==='synthetic_fixture';
  return <div className="site inv-site"><SiteHeader/>{synthetic&&<div className="inv-synthetic" role="note"><span className="shell">{investmentArchive.synthetic}</span></div>}<main id="main-content" tabIndex={-1} className="inv-main shell"><nav className="inv-breadcrumb" aria-label="Breadcrumb"><a href="/labs">Labs</a><span>/</span><a href="/botsquad">BotSquad</a><span>/</span><span>Investment</span></nav>
    <header className="inv-hero"><div><p className="eyebrow">The BotSquad investment experiment</p><h1>{copy.headline}</h1><p className="inv-intro">{copy.introduction}</p><div className="inv-actions"><a className="button button--primary" href="#desk">Explore the investment desk ↓</a><a href={inRun('/botsquad/investment/methodology',selectedRun)}>Read the methodology ↗</a></div></div><aside className="inv-hero-aside"><span className="inv-kicker">Research → discussion → decisions</span><h2>{copy.purpose}</h2><p>No real money. Workers may recommend BUY, SELL or HOLD; transactions are simulated. Performance is not guaranteed. Follow the evidence behind each conclusion.</p><p className="inv-meta">{copy.unstarted}</p></aside></header>
    <nav className="inv-index" aria-label="Showcase sections">{copy.navigation.map(([id,label],i)=><a key={id} href={'#'+id}><span aria-hidden="true">{String(i+1).padStart(2,'0')}</span>{label}</a>)}</nav>
<Suspense fallback={<p className="inv-empty" role="status">Loading verified archive records… The official experiment has not started.</p>}><ShowcaseRecords run={run}/></Suspense><p className="inv-footer-notice">{investmentArchive.notice}</p></main><SiteFooter/></div>;
}
function SectionHeading({number,title,description}:{number:string;title:string;description:string}){return <div className="inv-section-heading"><p className="inv-kicker">{number} / Investment experiment</p><h2>{title}</h2><p>{description}</p></div>;}
