import { ArchiveShell, Links, Sources } from '@/components/investment/archive';
import { AskPreview } from '@/components/investment/ask-preview';
import { archiveId, archiveRead } from '@/lib/investment-archive';
import { actorName, displayTime, recordHref } from '@/lib/investment-links';
import type { DecisionDetail } from '@/receiver/vendor/investment/v1/types';
export const dynamic='force-dynamic';
export const metadata={title:'Decision, evidence & outcome · BotSquad',robots:{index:false,follow:false}};
export default async function Page({params,searchParams}:{params:Promise<{decisionId:string}>;searchParams:Promise<{run?:string}>}) {
 const {decisionId}=await params,{run}=await searchParams,result=archiveId(decisionId)?await archiveRead<DecisionDetail>('decisions/'+decisionId,run):{data:null,error:'Invalid decision identity.'},d=result.data,p=d?.decision.payload.proposal;
 return <ArchiveShell title={p?`${p.action}: the decision and its evidence`:'Decision unavailable'} mode={d?.decision.evidenceMode} run={run} witness={result.data?result.fingerprint:undefined}>{d&&p?<><p className="archive-lead">{p.rationale}</p><p>{actorName(d.decision.actor)} · committed {displayTime(p.committedAt)} · revision {p.revision}</p><a href={recordHref({kind:'decision',id:p.decisionId,version:p.revision,relation:'supports'},d.runId)}>Permanent exact decision version →</a><section><h2>Alternatives & risks</h2><h3>Alternatives considered</h3><ul>{p.alternatives.map(x=><li key={x}>{x}</li>)}</ul><h3>Risks</h3><ul>{p.risks.map(x=><li key={x}>{x}</li>)}</ul><p>Invalidation condition: {p.invalidationCondition}</p><p>Evidence cutoff: {displayTime(p.evidenceCutoff)}</p></section><section><h2>Evidence behind the decision</h2><Links refs={[...p.evidence,...d.decision.references]} run={d.runId}/></section><Sources sources={p.sources}/><section><h2>Independent review & dissent</h2><p>{d.decision.payload.review.reviewerId} · {d.decision.payload.review.disposition} · {displayTime(d.decision.payload.review.reviewedAt)}</p><p>{d.decision.payload.review.rationale}</p><ul>{d.decision.payload.review.dissent.map(x=><li key={x}>{x}</li>)}</ul>{!d.decision.payload.review.dissent.length&&<p>No dissent was published with this review.</p>}<Links refs={d.decision.payload.review.evidence} run={d.runId}/></section><section><h2>Orders & simulated actions</h2>{p.action==='HOLD'&&<p>HOLD preserves the decision to wait. No order is required.</p>}{d.orders.length?<ul>{d.orders.map(o=><li key={o.orderId}><a href={recordHref({kind:'order',id:o.orderId,version:o.revision,relation:'results_in'},d.runId)}>{o.side} · {o.status} · {o.quantity} shares · exact revision {o.revision}</a><p>{o.reason??'Inspect the exact order for its constraints.'}</p></li>)}</ul>:p.action!=='HOLD'&&<p>No published order. A proposal alone does not establish execution.</p>}<h3>Completed financial effects</h3><Links refs={d.transactions} run={d.runId}/></section><section><h2>Later outcomes & review</h2><Links refs={d.reviews} run={d.runId}/>{!d.reviews.length&&<p>No later outcome can yet be assessed.</p>}</section><AskPreview label="Ask about this decision" context={{experimentId:d.experimentId,runId:d.runId,record:{kind:'decision',id:p.decisionId,version:p.revision,relation:'supports'}}}/></>:<p role="status">{result.error}</p>}</ArchiveShell>;
}
